### ISSUE TITLE
Consider support for simpler mDNS configuration

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/thing-url-adapter#15]
At least one embedded mDNS library doesn't support subtypes. We should consider one of three approaches:
1. Support or switch to _webthing._tcp
2. Support _http._tcp with a txt record of `webthing=true`
3. Fix any libraries that don't support subtypes (I'll conduct a quick survey tomorrow to see if this is widespread)

Do any of these approaches sound reasonable? Is there a good alternative I haven't covered?

**Comment by mdburmeisterbrown** [comment]
Either 1 or 2 have the advantage of not requiring library upgrades.  I have no preference between these alternatives.

3 also works if it is just the ESP library being a bit of a subset.    The ESP8266 represents a huge percentage of commercial (as well as maker) devices (eg, tuya.com) so we should make sure it is supported somehow.  For example, all our forthcoming IoT devices use ESP chipsets to date.

**Comment by mrstegeman** [comment]
I did run into several libraries without proper sub-type support (i.e. [bonjour](https://github.com/watson/bonjour/issues/1)), but was able to work around it or find a different library in all cases.

In my opinion:
1. Easiest option.
2. Probably better than 1, given that it really is pure HTTP.
3. The proper thing to do.

**Comment by hobinjk** [comment]
Here's the results of my initial survey of the landscape:
- [Arduino
  WiFi101](https://github.com/arduino-libraries/WiFi101/blob/master/src/WiFiMDNSResponder.cpp):
  Only does name requests
- [Espruino](http://www.espruino.com/Internet): No mDNS support, standard throughout tutorials is the board printing out an IP address
- [ESP AT+MDNS command](https://bbs.espressif.com/viewtopic.php?t=1714): Seems
  buggy, supports a "protocol name" of http but it's unclear whether that means
  it only supports _http._tcp or if it could do _webthing._tcp
- [pycom](https://docs.pycom.io/): Nothing yet
- [ESP32](https://github.com/espressif/arduino-esp32/blob/600f4c4130f2411e8ff33396d0ef40a7ec257cd6/tools/sdk/include/mdns/mdns.h): Full mdns support without subtypes
- [WICED](https://learn.adafruit.com/introducing-the-adafruit-wiced-feather-wifi/wiced-feather-api): No support

I think 2 is the best approach to support since that gets us support for ESP8266 and ESP32. I think it's also an easier target for modifying the WiFi101 library. Based on how most of the examples with the other boards tell the user to print out the IP address on a serial port I think it's reasonable to say that users of these boards should use Add Thing by URL with the IP address they're already getting.

**Comment by mrstegeman** [comment]
I'm fine with that. Should we support both `_webthing._tcp` and `_webthing._sub._http._tcp`, or just the former?

**Comment by hobinjk** [comment]
I think we should view _http._tcp with a txt record webthing=true to be just an alternate way of specifying the _webthing subtype and keep both supported.

**Comment by mrstegeman** [comment]
Agreed.
