### ISSUE TITLE
Not reconnecting to remote thing after network interruption

### ISSUE THREAD

**Issue by Timmeey** [mozilla-iot/thing-url-adapter#17]
After adding a remote Thing, when the thing goes down (network outage and whatnot), it doesn't reconnect to this thing after it is available again.

Reproduce:
1. Start remote web thing
2. add remote web thing as a thing
3. check that the thing is showing properly and is getting updates (fake sensor updating itself every few seconds)
4. disconnect/restart the remote web thing
5. the updating of the things sensor value in the UI stops
6. Wait a bit, reload the ui
7. Still not updating the things sensor value

Expected:
1. Start remote web thing
2. add remote web thing as a thing
3. check that the thing is showing properly and is getting updates (fake sensor updating itself every few seconds)
4. disconnect then reconnect XOR restart the remote web thing
5. the updating of the things sensor value in the UI stops
6. Wait a bit (maybe even reload the UI)
7. The things sensor reading is updating again

**Comment by hobinjk** [comment]
Oh, interesting. It's likely an issue with the websocket interface specifically then since the esp8266 doesn't do that. This should be enough information to get a fix done

**Comment by hobinjk** [comment]
You're welcome!

The thing-url-adapter polls the esp8266 every 5 seconds for changes

**Comment by mrstegeman** [comment]
It's possible that this isn't doing the right thing: https://github.com/mozilla-iot/thing-url-adapter/blob/master/thing-url-adapter.js#L226
