### ISSUE TITLE
Failed to remove Thing: Add already in progress

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/thing-url-adapter#20]
1. Add a discovered thing
2. Try to remove this thing
3. Remove fails with "Failed to remove Thing: Add already in progress"

Might be a Gateway issue, not sure exactly what's going on

**Comment by hobinjk** [comment]
as a bonus
4. Wait for a long time, remove succeeds

**Comment by hobinjk** [comment]
Likely a Gateway issue related to pairing needing a lot of time to be canceled for some reason

**Comment by mrstegeman** [comment]
I see this frequently, as well.

**Comment by mrstegeman** [comment]
I can confirm that this happens with other add-ons as well. Moving to gateway.

**Comment by mrstegeman** [comment]
https://github.com/mozilla-iot/gateway/issues/885
