### ISSUE TITLE
Failed to manual install

### ISSUE THREAD

**Issue by OlavGullaksen** [mozilla-iot/thing-url-adapter#24]
Hi there,
I followed the instructions for manual installation in the Readme file and it looks like the shell script has errors:
![image](https://user-images.githubusercontent.com/10128386/38467757-37d1270e-3b3d-11e8-8213-f5b6554a56f1.png)
I have the application running on a RPi 3 originally installed with the Mozilla IoT image downloaded and updated with apt-get update and apt-get upgrade commands. When will version 0.4 be released? I can see the thing-url-adapter will be pre-installed with this revision and this could solve my current issues.
Thanks a lot for your efforts.

**Comment by mrstegeman** [comment]
If you're running with the master branch of the gateway (and are updated to the latest HEAD), you can now install this add-on via the UI instead of manually.

If, however, you're running one of the 0.3.X releases, you can make the `package.sh` script work as follows:
```
$ npm i -g yarn  # you may have to run this as 'sudo'
$ ./package.sh   # do NOT run as `sh package.sh`
```
