### ISSUE TITLE
Watch for things which no longer exist

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/thing-url-adapter#51]
If a thing disappears on the network, we should call `removeThing()`.

**Comment by benfrancis** [comment]
Is this for mDNS broadcasts and/or Bluetooth beacons?

How does the mDNS scanning work exactly? Why do devices that are no longer broadcasting appear in the list? Presumably they're being cached rather than actively scanned for?

What would qualify something as having disappeared?

**Comment by mrstegeman** [comment]
@benfrancis Yes. Once they're discovered by the adapter, we never really check that they're still active and prune dead nodes. For instance, if I have a web thing plugged into the wall, and I decide I no longer want it, it will never be removed from the adapter after I unplug it.

**Comment by mrstegeman** [comment]
Fixed by #55
