### ISSUE TITLE
Things adapter parses WebThing API description wrongly

### ISSUE THREAD

**Issue by dvas0004** [mozilla-iot/thing-url-adapter#62]
**Symptoms:**

- When adding a new WebThings item via mDNS, no properties are shown
- When adding a new WebThings item via URL, properties are shown but without any values (see screenshot below), and disappear on refresh

![screenshot from 2018-12-05 12-46-03](https://user-images.githubusercontent.com/5849965/49519604-095cb700-f8aa-11e8-9022-51f18becb23a.png)

**Reproduction:**

- Use Mozilla IoT Gateway RaspPi Image, and install+enable WebThings adapter:

![screenshot from 2018-12-05 16-24-17](https://user-images.githubusercontent.com/5849965/49519697-46c14480-f8aa-11e8-8f6f-a8c140c80593.png)

- Setup a basic WebThing-Node as per [README in the Github repo](https://github.com/mozilla-iot/webthing-node)
- Run the node example and in IoT gateway, add a thing. Select the mDNS hostname, and you'll see missing properties or properties without values

**Expected:**

![screenshot from 2018-12-05 13-40-21](https://user-images.githubusercontent.com/5849965/49519868-ad466280-f8aa-11e8-9088-471c19f6a54c.png)

Note in the above screenshot the "brightness" is populated with 50% and basically everything works as expected

**Troubleshooting / Potential Solution:**

Looking at the run-app logs, we see some interesting entries:

![screenshot from 2018-12-05 12-43-33](https://user-images.githubusercontent.com/5849965/49519974-f0083a80-f8aa-11e8-8895-5370acfa5353.png)

Note the "undefined" being appended to the URL. Searching for the error message "Failed to connect..." in thing-url-adapter.js, I managed to [trace the error to line 105](https://github.com/mozilla-iot/thing-url-adapter/blob/master/thing-url-adapter.js#L105). 

Currently you expect a single 'href' to be present in JSON returned from the WebThings API, however what's being returned is actually a "links" array, which then contains the 'href' string you are looking for, for example:

```json
{"name":"MacDetector","href":"/","@context":"https://iot.mozilla.org/schemas","@type":[],"properties":{"DavidPresent":{"@type":"OnOffProperty","label":"David Present","type":"boolean","description":"If David MAC address is present","readOnly":false,"links":[{"rel":"property","href":"/properties/DavidPresent"}]},
...
```

Changing line 105 in thing-url-adapter.js to:

```
const propertyUrl = this.baseUrl + propertyDescription.links[0].href;
```
solves the issue

Notes to anyone trying the above workaround:
- You need to first update the SHA256SUMS entry for thing-url-adapter.js, and restart 

- All the files mentioned above are installed under **/home/pi/.mozilla-iot/addons/thing-url-adapter**

**Comment by mrstegeman** [comment]
Do you have any other details? What's being parsed improperly?

**Comment by dvas0004** [comment]
Sorry @mrstegeman! I was click-happy and created the issue without adding the description. Issue updated :)

**Comment by mrstegeman** [comment]
@dvas0004 Yeah, the webthing libraries were all just updated for the latest spec, but the adapter has not yet been updated. If you have an immediate need, you can step back to the 0.9.X library series. Otherwise, I plan to update the add-on this week.

**Comment by dvas0004** [comment]
No worries! The workaround I described is working sufficiently for me at
the moment :)
