### ISSUE TITLE
ESP8266 is disconnected

### ISSUE THREAD

**Issue by PPCM** [mozilla-iot/thing-url-adapter#80]
Hello there,

I made a simple webthing with Wemos D1 Mini.
The source file is joined to this post.
[Wifi_led.ino.txt](https://github.com/mozilla-iot/gateway/files/3884253/Wifi_led.ino.txt)

The connection to the WIFI and WebThings Gateway is done correctly. I can control the led without problem.
But if there is no action after one or two minutes on the device, it is disconnected from WebThings Gateway.

Some investigations :
- The WIFI connection of the device is still active
- The device responds to pings
- The WebThings Gateway responds for other devices

To reconnect the device to the gateway, the device has to be reseted.

How to make a stable permanent?

**Comment by mrstegeman** [comment]
* Are you using the WebSocket version of the library, i.e. you have not defined `WITHOUT_WS`?
* What version of the "Web Thing" add-on is your gateway using?
* Is your device dropping into a low power mode or something?

**Comment by PPCM** [comment]
I don't know which version of the library I use, I downloaded it from here: 
https://github.com/mozilla-iot/webthing-arduino/releases

I use WebThing 0.4.1 on the gateway, but I didn't add any URL of the ESP8266 device, I simply add the device with the + button.

I don't think the device is low power mode because it responds to pings and direct access to the ESP8266 webserver succeed

**Comment by PPCM** [comment]
@mrstegeman Your post made me think about the way I added the device.
So I changed the procedure:

- Previously
When I added an element, I used the "+" button in "Things" menu, and the gateway recognized automatically the device.
With the procedure, the device is deconnected after one or two minutes.

- Now
When I add an element, I use the "+" button in "Things" menu, then I use "Add by URL..." link.
Now the device is no more disconnected.

That's mean there are 2 ways to add a new device, one works fine and the second doesn't work correctly.
Perhaps, it will be good if only one way becomes available.

An other reflection: my devices are on a network with a DHCP server, what happen if the device changes its IP address?
Does the gateway store devices with there MAC Address?

**Comment by mrstegeman** [comment]
Ah, good. Glad that's working for you. It seems like there's probably an mDNS issue, then. Lots of those seem to exist with the ESP mDNS libraries: https://github.com/mozilla-iot/webthing-arduino/issues

> An other reflection: my devices are on a network with a DHCP server, what happen if the device changes its IP address?

The device will become disconnected. You're best off assigning a static IP to your device, if possible.

> Does the gateway store devices with there MAC Address?

No. Ideally, mDNS resolves those issues. However, that doesn't seem to work all the time.

**Comment by PPCM** [comment]
I notice an other issue now.
When I plug off the device, it is still actice on the gateway. I can change its state, but if I reload the page, the state of the device stay on the state when it was unplugged.
Not ideal ...
