### ISSUE TITLE
gateway continuously tries to reach a webthing that is offline

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/thing-url-adapter#86]
simple "Hello LED" webthing has JSON that looks like this:

`
{ "name": "Hello LED",
  "@context": "https://iot.mozilla.org/schemas/",
  "@type": ["Light"],
  "properties": {
    "on": {"title": "Lit", 
    "type": "boolean", 
    "href": "/properties/on", 
    "@type": "OnOffProperty"}
    }
  }
`

It is visible in a browser by IP address (this device does not do mDNS but the problem exists whether it does or not). After adding it to the gateway and then disconnecting it, the log shows repeated attempts to reach it. 

`2019-05-27 21:16:20.420 INFO   : thing-url: Failed to connect to http://192.168.30.161/properties/on: FetchError: request to http://192.168.30.161/properties/on failed, reason: connect EHOSTUNREACH 192.168.30.161:80`
`2019-05-27 21:16:20.422 INFO   : thing-url: Failed to connect to http://192.168.30.161/properties/on: FetchError: request to http://192.168.30.161/properties/on failed, reason: connect EHOSTUNREACH 192.168.30.161:80`
`2019-05-27 21:16:20.424 INFO   : thing-url: Failed to connect to http://192.168.30.161/properties/on: FetchError: request to http://192.168.30.161/properties/on failed, reason: connect EHOSTUNREACH 192.168.30.161:80`

and so on... (causing the RPi to be very busy and clog the network with requests)

Upon restarting the "Web Thing" Add-on (v0.2.8), the continuous attempts in the log stop.

Next the "Hello LED" thing was plugged back in. The gateway did not automatically find it. After pressing "+" on the Things page, then it was active and controllable again.

In addition to the main bug of a webthing going offline and the gw continuously searchin for it, when a webthing does come back online on a network, should it do something to announce itself so that the gateway doesn't have to constantly look for it? And if the gateway does need to periodically poll for offline devices to figure out when they come back online, how often does or should that occur?

This problem of continuous searching occurs even if you remove (delete) the offline thing from the Things page. Fortunately, the workaround to disable then enable the Web Thing Add-on stops the recurring attempts to reach the offline device.

**Comment by mrstegeman** [comment]
Note to self: use `handleDeviceSaved()` to figure out which devices to poll.
