### ISSUE TITLE
Handle multiple propertyStatus updates per message

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/thing-url-adapter#87]
The webthing-arduino library may include updates for multiple properties in a single propertyStatus message, but that's not currently handled properly.

@ShawnHymel this is the bug from your latest video. I'll get it fixed in a few days.

**Comment by ShawnHymel** [comment]
Thanks for submitting the issue. I really thought it was already logged as an issue, otherwise I would have reported it! Apologies!
